openapi: 3.1.0
info:
  version: 1.0.0
  title: Radial app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: <опис вашого додатку>
tags:
  # теги, що ви будете використовувати
  #   - name: Students
  #   description: Operations about users.
  # - name: Auth
  #   description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-8q3t.onrender.com
paths:
  # тут будуть посилання на ендпоінти
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
